#!/bin/bash

# -------------------------------------------------------------------
# escape: Escape UTF-8 characters into their 3-byte format
escape() 
{
  printf "\\\x%s" $(printf "$@" | xxd -p -c1 -u)
  # print a newline unless we’re piping the output to another program
  if [ -t 1 ]; then
    echo # newline
  fi
}
