#!/bin/bash

# -------------------------------------------------------------------
# httpDebug: download a web page and show info on what took time
#
# usage -> httpDebug http://github.com
httpDebug()
{
  curl $@ -o /dev/null -w "dns: %{time_namelookup} connect: %{time_connect} pretransfer: %{time_pretransfer} starttransfer: %{time_starttransfer} total: %{time_total}\n"
}
