#!/bin/sh

export PERL_MB_OPT="--install_base \"$HOME/.local/opt/perl\"";
export PERL_MM_OPT="INSTALL_BASE=$HOME/.local/opt/perl";
export CPAN_HOME="$HOME/.local/opt/perl/cpan";
export PERL5LIB="$HOME/.local/lib/perl:$HOME/.local/opt/perl/lib/perl5";
/bin/mkdir -p "$HOME/.local/lib/perl"
/bin/mkdir -p "$HOME/.local/opt/perl/lib/perl5"

if [ -e /usr/bin/perlbrew ]; then
	export PERLBREW_ROOT=~/.local/opt/perl

	if [ ! -e ${PERLBREW_ROOT}/etc/bashrc ]; then
		perlbrew init
	fi

	if [ -e ${PERLBREW_ROOT}/etc/bashrc ]; then
		source ${PERLBREW_ROOT}/etc/bashrc
	fi
else
	if [ -d ~/.local/opt/perl/bin ] ; then
		PATH=~/.local/opt/perl/bin:"${PATH}"
	fi
fi
