#!/bin/bash

if [ -z ${PKG_CONFIG_PATH} ]; then
	export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig
else
	export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig:${PKG_CONFIG_PATH}
fi

if [ -d /opt/local/lib/pkgconfig ]; then
	if [[ ! ":PKG_CONFIG_PATH:" == *":/opt/local/lib/pkgconfig:"* ]]; then
		export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/opt/local/lib/pkgconfig
	fi
fi

if [ -d /usr/local/lib/pkgconfig ]; then
	if [[ ! ":PKG_CONFIG_PATH:" == *":/usr/local/lib/pkgconfig:"* ]]; then
		export PKG_CONFIG_PATH=${PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig
	fi
fi
