#!/bin/bash

# -------------------------------------------------------------------
# stripspace: strip unnecessary whitespace from file
stripspace() 
{
  if [ $# -eq 0 ]; then
    echo "Usage: stripspace FILE"
  else
    local tempfile=mktemp
    git stripspace < "$1" > tempfile
    mv tempfile "$1"
  fi
}
