#!/bin/bash

nvm_update() {
	if [ -d $HOME/.nvm/.git ]; then
		pushd $HOME/.nvm/.git > /dev/null
		git pull
		popd > /dev/null
	else
		git clone https://github.com/nvm-sh/nvm $HOME/.nvm
	fi
}

if [ -d $HOME/.nvm ]; then
	export NVM_DIR="$HOME/.nvm"
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi 
