#!/bin/bash
# Post-install hook for user package.
# Symlink dotfiles from the stow-managed etc/ into $HOME.
set -eu

ETC="$HOME/.local/etc"

ln -sf "$ETC/bashrc"        "$HOME/.bashrc"
ln -sf "$ETC/bash_profile"  "$HOME/.bash_profile"
ln -sf "$ETC/bash_logout"   "$HOME/.bash_logout"
ln -sf "$ETC/profile"       "$HOME/.profile"
ln -sf "$ETC/inputrc"       "$HOME/.inputrc"
[ -d "$ETC/bash" ] && ln -sf "$ETC/bash" "$HOME/.bash"
