#!/bin/sh

# Benachrichtigungen bei langen Prozessen
# sudo apt-get install libnotify-bin
# see http://linuxundich.de/de/ubuntu/benachrichtigungen-beim-beenden-langwieriger-prozesse/
# example wget http://speedtest.netcologne.de/test_1mb.bin; alert
if [ -x /usr/bin/notify-send ]; then
	alias alert='notify-send -i gnome-terminal "[$?] $(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/;\s*alert$//'\'')"'
	# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi
