#!/bin/bash

# -------------------------------------------------------------------
# json: Syntax-highlight JSON strings or files
#
# usage -> `json '{"foo":42}'` or `echo '{"foo":42}' | json`
json()
{
  if [ -t 0 ]; then # argument
    python -mjson.tool <<< "$*" | pygmentize -l javascript
  else # pipe
    python -mjson.tool | pygmentize -l javascript
  fi
}
