#!/bin/bash

# -------------------------------------------------------------------
# phpserver: Start a PHP server from a directory, optionally specifying the port
# (Requires PHP 5.4.0+.)
#
# usage:
# phpserver [port=4000] [ip=127.0.0.1]
phpserver()
{
  local free_port=$(netstat_free_local_port)
  local port="${1:-${free_port}}"
  local ip="${2:-127.0.0.1}"
  sleep 1 && xdg-open "http://${ip}:${port}/" &
  php -S "${ip}:${port}"
}
