#!/bin/bash

# -------------------------------------------------------------------
# connection_overview: get stats-overview about your connections
netstat_connection_overview()
{
  netstat -nat | awk '{print $6}' | sort | uniq -c | sort -n
}
