#!/bin/bash

if [ -f $HOME/.config/x509/ca-bundle.crt ]; then
	export SSL_CERT_FILE=$HOME/.config/x509/ca-bundle.crt
elif [ -f /etc/x509/ca-bundle.crt ]; then
	export SSL_CERT_FILE=/etc/x509/ca-bundle.crt
fi
